import type { Filter } from '../types';

/**
 * Converts a filter type to its corresponding CSS class or Canvas filter string.
 * @param filter The filter type.
 * @param forCanvas If true, returns a string suitable for the Canvas context's `filter` property.
 *                  If false, returns a Tailwind CSS class name.
 * @returns The CSS class or Canvas filter string.
 */
export const getFilterClass = (filter: Filter, forCanvas: boolean): string => {
    // Note: Tailwind classes are provided for best-effort preview. 
    // Complex combinations use arbitrary values which are supported by JIT, but canvas is the source of truth for saving.
    const filters: Record<Filter, { canvas: string, tailwind: string }> = {
        'none': { canvas: '', tailwind: '' },
        'grayscale': { canvas: 'grayscale(1)', tailwind: 'grayscale' },
        'sepia': { canvas: 'sepia(1)', tailwind: 'sepia' },
        'invert': { canvas: 'invert(1)', tailwind: 'invert' },
        'hue-rotate-90': { canvas: 'hue-rotate(90deg)', tailwind: 'hue-rotate-90' },
        'contrast': { canvas: 'contrast(1.5)', tailwind: 'contrast-150' },
        'saturate': { canvas: 'saturate(2)', tailwind: 'saturate-200' },
        'noir': { canvas: 'grayscale(1) contrast(1.3) sepia(0.2)', tailwind: 'grayscale sepia-[.2] contrast-[1.3]' },
        'vintage': { canvas: 'sepia(0.6) contrast(1.1) brightness(0.9) saturate(1.2)', tailwind: 'sepia-[.6] contrast-110 brightness-90 saturate-125' },
        'dreamy': { canvas: 'saturate(1.5) contrast(1.1) blur(2px)', tailwind: 'saturate-150 contrast-110 blur-[2px]' },
        'cyberpunk': { canvas: 'contrast(1.4) saturate(1.8) brightness(0.8) hue-rotate(200deg) sepia(0.3)', tailwind: 'contrast-[1.4] saturate-[1.8] brightness-75 hue-rotate-[200deg] sepia-[.3]' },
        'toon': { canvas: 'contrast(1.8) brightness(1.1) saturate(1.8)', tailwind: 'contrast-[1.8] brightness-110 saturate-[1.8]' },
        'bright': { canvas: 'brightness(1.5)', tailwind: 'brightness-150' },
        'blurry': { canvas: 'blur(4px)', tailwind: 'blur-md' },
        'warm': { canvas: 'sepia(0.4) saturate(1.5)', tailwind: 'sepia-[.4] saturate-150' },
        'cool': { canvas: 'contrast(1.1) brightness(1.1)', tailwind: 'contrast-110 brightness-110' },
        'charcoal': { canvas: 'grayscale(1) contrast(2) brightness(0.8)', tailwind: 'grayscale contrast-200 brightness-75' },
        'silver': { canvas: 'grayscale(1) brightness(1.2) contrast(1.1)', tailwind: 'grayscale brightness-125 contrast-110' },
        'old-west': { canvas: 'sepia(0.8) contrast(1.2) brightness(0.8) saturate(1.2)', tailwind: 'sepia-[.8] contrast-125 brightness-75 saturate-125' },
        'seventies': { canvas: 'sepia(0.5) hue-rotate(-30deg) saturate(1.4) contrast(0.9)', tailwind: 'sepia-[.5] hue-rotate-[-30deg] saturate-150 contrast-90' },
        'faded': { canvas: 'contrast(0.8) brightness(1.1) saturate(0.8)', tailwind: 'contrast-75 brightness-110 saturate-75' },
        'electric': { canvas: 'saturate(3) contrast(1.5) hue-rotate(45deg)', tailwind: 'saturate-200 contrast-150 hue-rotate-[45deg]' },
        'hypercolor': { canvas: 'saturate(2.5) contrast(1.2) brightness(1.1) hue-rotate(-45deg)', tailwind: 'saturate-200 contrast-125 brightness-110 hue-rotate-[-45deg]' },
        'neon': { canvas: 'brightness(1.4) contrast(1.5) saturate(2) hue-rotate(290deg)', tailwind: 'brightness-150 contrast-150 saturate-200 hue-rotate-[290deg]' },
        'sketch': { canvas: 'grayscale(1) invert(1) contrast(2) brightness(2)', tailwind: 'grayscale invert contrast-200 brightness-200' },
        'crimson': { canvas: 'sepia(0.5) saturate(2) hue-rotate(-20deg) contrast(1.1)', tailwind: 'sepia-[.5] saturate-200 hue-rotate-[-20deg] contrast-110' },
        'emerald': { canvas: 'hue-rotate(40deg) saturate(1.5) contrast(1.1) brightness(0.9)', tailwind: 'hue-rotate-[40deg] saturate-150 contrast-110 brightness-90' },
        'sapphire': { canvas: 'hue-rotate(-120deg) saturate(1.8) contrast(1.1)', tailwind: 'hue-rotate-[-120deg] saturate-200 contrast-110' },
        'gold': { canvas: 'sepia(0.6) saturate(1.5) contrast(1.1) brightness(1.1)', tailwind: 'sepia-[.6] saturate-150 contrast-110 brightness-110' },
        'lavender': { canvas: 'hue-rotate(240deg) saturate(1.4) brightness(1.2)', tailwind: 'hue-rotate-[240deg] saturate-150 brightness-125' },
        'rose-tint': { canvas: 'sepia(0.2) hue-rotate(-10deg) saturate(1.3)', tailwind: 'sepia-[.2] hue-rotate-[-10deg] saturate-125' },
        'melancholy': { canvas: 'grayscale(0.5) contrast(1.1) brightness(0.9)', tailwind: 'grayscale-[.5] contrast-110 brightness-90' },
        'serene': { canvas: 'saturate(0.8) brightness(1.1) contrast(0.9)', tailwind: 'saturate-75 brightness-110 contrast-90' },
        'energetic': { canvas: 'saturate(1.8) contrast(1.2) brightness(1.1)', tailwind: 'saturate-200 contrast-125 brightness-110' },
        'romantic': { canvas: 'saturate(1.3) contrast(1.1) brightness(1.1) sepia(0.3)', tailwind: 'saturate-125 contrast-110 brightness-110 sepia-[.3]' },
        'eerie': { canvas: 'hue-rotate(180deg) contrast(1.4) brightness(0.7) saturate(0.5)', tailwind: 'hue-rotate-180 contrast-150 brightness-75 saturate-50' },
        'sharpen': { canvas: 'contrast(1.4) brightness(1.1)', tailwind: 'contrast-150 brightness-110' },
        'darken': { canvas: 'brightness(0.7) contrast(1.2)', tailwind: 'brightness-75 contrast-125' },
        'oceanic': { canvas: 'saturate(1.2) contrast(1.1) hue-rotate(-160deg)', tailwind: 'saturate-125 contrast-110 hue-rotate-[-160deg]' },
        'sunset': { canvas: 'sepia(0.4) saturate(1.6) contrast(1.1) hue-rotate(-20deg)', tailwind: 'sepia-[.4] saturate-150 contrast-110 hue-rotate-[-20deg]' },
        'forest': { canvas: 'contrast(1.2) saturate(1.4) sepia(0.2) hue-rotate(20deg)', tailwind: 'contrast-125 saturate-150 sepia-[.2] hue-rotate-[20deg]' },
        'winter': { canvas: 'saturate(0) contrast(1.2) brightness(1.1)', tailwind: 'saturate-0 contrast-125 brightness-110' },
        'summer': { canvas: 'saturate(1.6) contrast(1.1) brightness(1.1)', tailwind: 'saturate-150 contrast-110 brightness-110' },
        'spring': { canvas: 'saturate(1.4) sepia(0.1) contrast(1.1)', tailwind: 'saturate-150 sepia-[.1] contrast-110' },
        'autumn': { canvas: 'sepia(0.5) saturate(1.5) hue-rotate(-30deg)', tailwind: 'sepia-[.5] saturate-150 hue-rotate-[-30deg]' },
        'x-pro': { canvas: 'sepia(0.3) contrast(1.5) brightness(0.8) saturate(1.8)', tailwind: 'sepia-[.3] contrast-150 brightness-75 saturate-200' },
        'lo-fi': { canvas: 'saturate(1.1) contrast(1.5)', tailwind: 'saturate-110 contrast-150' },
        'nashville': { canvas: 'sepia(0.2) contrast(1.5) brightness(0.9) hue-rotate(-30deg)', tailwind: 'sepia-[.2] contrast-150 brightness-90 hue-rotate-[-30deg]' },
        'inkwell': { canvas: 'grayscale(1) contrast(1.1) brightness(1.1)', tailwind: 'grayscale contrast-110 brightness-110' },
        'hefe': { canvas: 'contrast(1.5) sepia(0.4) saturate(1.5)', tailwind: 'contrast-150 sepia-[.4] saturate-150' },
        'valencia': { canvas: 'sepia(0.15) saturate(1.5) contrast(1.1)', tailwind: 'sepia-[.15] saturate-150 contrast-110' },
        'hudson': { canvas: 'brightness(1.2) contrast(0.9) saturate(1.1)', tailwind: 'brightness-125 contrast-90 saturate-110' },
        'brannan': { canvas: 'sepia(0.4) contrast(1.4)', tailwind: 'sepia-[.4] contrast-150' },
        'earlybird': { canvas: 'sepia(0.4) contrast(1.2) brightness(0.9) saturate(1.2)', tailwind: 'sepia-[.4] contrast-125 brightness-90 saturate-125' },
        'sierra': { canvas: 'sepia(0.25) contrast(1.5) brightness(0.8)', tailwind: 'sepia-[.25] contrast-150 brightness-75' },
        'walden': { canvas: 'sepia(0.3) saturate(1.6) brightness(1.1)', tailwind: 'sepia-[.3] saturate-150 brightness-110' },
        'toaster': { canvas: 'sepia(0.4) saturate(2.5) contrast(1.5) hue-rotate(-30deg)', tailwind: 'sepia-[.4] saturate-200 contrast-150 hue-rotate-[-30deg]' },
        'poprocket': { canvas: 'sepia(0.15) brightness(1.2)', tailwind: 'sepia-[.15] brightness-125' },
        'gotham': { canvas: 'grayscale(1) contrast(1.5) brightness(0.9)', tailwind: 'grayscale contrast-150 brightness-90' },
        'lomo': { canvas: 'saturate(1.5) contrast(1.2) sepia(0.2)', tailwind: 'saturate-150 contrast-125 sepia-[.2]' },
        'kelvin': { canvas: 'sepia(0.4) saturate(2) brightness(1.2) contrast(1.1)', tailwind: 'sepia-[.4] saturate-200 brightness-125 contrast-110' },
        'maven': { canvas: 'sepia(0.25) saturate(1.5) contrast(0.95) brightness(0.95)', tailwind: 'sepia-[.25] saturate-150 contrast-95 brightness-95' },
        'moon': { canvas: 'grayscale(1) contrast(1.1) brightness(1.1)', tailwind: 'grayscale contrast-110 brightness-110' },
        'gingham': { canvas: 'brightness(1.05) hue-rotate(-10deg)', tailwind: 'brightness-105 hue-rotate-[-10deg]' },
        'clarendon': { canvas: 'contrast(1.2) saturate(1.35)', tailwind: 'contrast-125 saturate-125' },
        'reyes': { canvas: 'sepia(0.22) brightness(1.1) contrast(0.85) saturate(0.75)', tailwind: 'sepia-[.22] brightness-110 contrast-85 saturate-75' },
        'slumber': { canvas: 'saturate(0.66) brightness(1.05)', tailwind: 'saturate-50 brightness-105' },
        'crema': { canvas: 'sepia(0.5) contrast(1.2) saturate(1.4)', tailwind: 'sepia-[.5] contrast-125 saturate-150' },
        'perpetua': { canvas: 'contrast(1.1) saturate(1.2) brightness(1.1)', tailwind: 'contrast-110 saturate-125 brightness-110' },
        'amaro': { canvas: 'hue-rotate(-10deg) contrast(0.9) brightness(1.1) saturate(1.5)', tailwind: 'hue-rotate-[-10deg] contrast-90 brightness-110 saturate-150' },
        'mayfair': { canvas: 'contrast(1.1) saturate(1.1)', tailwind: 'contrast-110 saturate-110' },
        'rise': { canvas: 'brightness(1.05) sepia(0.2) contrast(0.9) saturate(0.9)', tailwind: 'brightness-105 sepia-[.2] contrast-90 saturate-90' },
        'willow': { canvas: 'grayscale(0.5) contrast(0.95) brightness(0.9)', tailwind: 'grayscale-[.5] contrast-95 brightness-90' },
        'xpro2': { canvas: 'sepia(0.3) contrast(1.5) brightness(0.8) saturate(1.8)', tailwind: 'sepia-[.3] contrast-150 brightness-75 saturate-200' },
        'aden': { canvas: 'hue-rotate(-20deg) contrast(0.9) saturate(0.85) brightness(1.2)', tailwind: 'hue-rotate-[-20deg] contrast-90 saturate-75 brightness-125' },
        'lark': { canvas: 'contrast(0.9) saturate(1.1)', tailwind: 'contrast-90 saturate-110' },
        'juno': { canvas: 'contrast(1.2) brightness(1.1) saturate(1.4) sepia(0.2)', tailwind: 'contrast-125 brightness-110 saturate-150 sepia-[.2]' },
        'ludwig': { canvas: 'brightness(1.05) saturate(1.3) contrast(0.95)', tailwind: 'brightness-105 saturate-125 contrast-95' },
        'inkwell-dark': { canvas: 'grayscale(1) brightness(0.8) contrast(1.3)', tailwind: 'grayscale brightness-75 contrast-125' },
        'mono-tint': { canvas: 'grayscale(1) sepia(0.2)', tailwind: 'grayscale sepia-[.2]' },
        'arctic': { canvas: 'brightness(1.1) contrast(1.1) saturate(0.2) sepia(0.1)', tailwind: 'brightness-110 contrast-110 saturate-0 sepia-[.1]' },
        'desert': { canvas: 'sepia(0.6) brightness(1.1) contrast(1.1)', tailwind: 'sepia-[.6] brightness-110 contrast-110' },
        'matrix': { canvas: 'contrast(1.5) saturate(1.8) hue-rotate(60deg) sepia(0.3)', tailwind: 'contrast-150 saturate-200 hue-rotate-[60deg] sepia-[.3]' },
        'radioactive': { canvas: 'hue-rotate(90deg) contrast(1.2) brightness(1.2) saturate(2)', tailwind: 'hue-rotate-90 contrast-125 brightness-125 saturate-200' },
        'fireball': { canvas: 'saturate(2) contrast(1.5) hue-rotate(-30deg) brightness(1.1)', tailwind: 'saturate-200 contrast-150 hue-rotate-[-30deg] brightness-110' },
        'ice-cold': { canvas: 'brightness(1.1) contrast(1.2) saturate(0.5) hue-rotate(-180deg)', tailwind: 'brightness-110 contrast-125 saturate-50 hue-rotate-180' },
        'deep-purple': { canvas: 'hue-rotate(270deg) saturate(1.5) contrast(1.1) brightness(1.1)', tailwind: 'hue-rotate-[270deg] saturate-150 contrast-110 brightness-110' },
        'aqua': { canvas: 'saturate(1.5) hue-rotate(-170deg)', tailwind: 'saturate-150 hue-rotate-[-170deg]' },
        'sun-kissed': { canvas: 'sepia(0.2) contrast(1.1) brightness(1.1) saturate(1.3)', tailwind: 'sepia-[.2] contrast-110 brightness-110 saturate-125' },
        'golden-hour': { canvas: 'sepia(0.4) contrast(1.1) brightness(1.05) saturate(1.4)', tailwind: 'sepia-[.4] contrast-110 brightness-105 saturate-150' },
        'blue-lagoon': { canvas: 'contrast(1.1) saturate(1.4) hue-rotate(-180deg)', tailwind: 'contrast-110 saturate-150 hue-rotate-180' },
        'mystic': { canvas: 'sepia(0.2) contrast(1.2) saturate(0.8) hue-rotate(220deg)', tailwind: 'sepia-[.2] contrast-125 saturate-75 hue-rotate-[220deg]' },
        'retro-future': { canvas: 'sepia(0.5) hue-rotate(-60deg) saturate(1.5)', tailwind: 'sepia-[.5] hue-rotate-[-60deg] saturate-150' },
        'dream-pop': { canvas: 'brightness(1.15) saturate(1.4) contrast(1.05) blur(2px)', tailwind: 'brightness-110 saturate-[1.4] contrast-105 blur-[2px]' },
        'noir-comic': { canvas: 'grayscale(1) contrast(2) brightness(1.1)', tailwind: 'grayscale contrast-200 brightness-110' },
        'acid-wash': { canvas: 'contrast(1.5) saturate(1.5) invert(1) hue-rotate(180deg)', tailwind: 'contrast-150 saturate-150 invert hue-rotate-180' },
        'polaroid': { canvas: 'sepia(0.35) contrast(1.1) brightness(1.1) saturate(1.2)', tailwind: 'sepia-[.35] contrast-110 brightness-110 saturate-125' },
        'daguerreotype': { canvas: 'sepia(0.7) contrast(1.3) brightness(0.9) grayscale(0.2)', tailwind: 'sepia-[.7] contrast-125 brightness-90 grayscale-[.2]' },
        'technicolor-dream': { canvas: 'saturate(2.5) contrast(1.3) hue-rotate(45deg)', tailwind: 'saturate-200 contrast-125 hue-rotate-45' },
        'cotton-candy': { canvas: 'saturate(1.5) contrast(1.1) brightness(1.1) hue-rotate(-30deg)', tailwind: 'saturate-150 contrast-110 brightness-110 hue-rotate-[-30deg]' },
        'midnight': { canvas: 'brightness(0.6) contrast(1.4) saturate(0.4)', tailwind: 'brightness-50 contrast-150 saturate-50' },
        'aurora': { canvas: 'hue-rotate(120deg) saturate(1.8) brightness(1.1) contrast(1.2)', tailwind: 'hue-rotate-[120deg] saturate-200 brightness-110 contrast-125' },
        'candy-apple': { canvas: 'saturate(1.8) contrast(1.2) hue-rotate(-15deg)', tailwind: 'saturate-200 contrast-125 hue-rotate-[-15deg]' },
        'faded-glory': { canvas: 'saturate(0.6) contrast(1.1) sepia(0.3)', tailwind: 'saturate-50 contrast-110 sepia-[.3]' },
        'cinematic-teal': { canvas: 'sepia(0.3) contrast(1.25) brightness(0.9) hue-rotate(180deg) saturate(1.1)', tailwind: 'sepia-[.3] contrast-125 brightness-90 hue-rotate-180 saturate-110' },
        'moody-film': { canvas: 'saturate(0.5) contrast(1.2) brightness(0.95) sepia(0.15)', tailwind: 'saturate-50 contrast-125 brightness-95 sepia-[.15]' },
        'soft-glow': { canvas: 'saturate(1.1) contrast(1.05) brightness(1.1) blur(1.5px)', tailwind: 'saturate-110 contrast-105 brightness-110 blur-[1.5px]' },
        'vintage-fade': { canvas: 'sepia(0.3) contrast(0.9) brightness(1.1) saturate(1.1)', tailwind: 'sepia-[.3] contrast-90 brightness-110 saturate-110' },
        'emerald-tint': { canvas: 'sepia(0.2) contrast(1.1) brightness(0.9) saturate(1.5) hue-rotate(60deg)', tailwind: 'sepia-[.2] contrast-110 brightness-90 saturate-150 hue-rotate-[60deg]' },
        'glitch': { canvas: '', tailwind: 'saturate-200 hue-rotate-[15deg] contrast-150' },
        'scanlines': { canvas: '', tailwind: '' },
    };

    const selectedFilter = filters[filter] || filters['none'];
    return forCanvas ? selectedFilter.canvas : selectedFilter.tailwind;
};